Limited -D debug print statements unless compiled with -DDEBUG

diff --git a/test/tst b/test/tst
--- a/test/tst
+++ b/test/tst
@@ -7,18 +7,25 @@ TEN_PLUSS=++++++++++
 #
 echo "$TEN_PLUSS ihad test00.dat  +++Zero Length File check${TEN_PLUSS}"
 ../ihad test00.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test01.dat  +++1 byte Length File check${TEN_PLUSS}"
 ../ihad test01.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test15.dat  +++15 byte Length File check${TEN_PLUSS}"
 ../ihad test15.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test16.dat  +++16 byte Length File check${TEN_PLUSS}"
 ../ihad test16.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test17.dat  +++17 byte Length File check${TEN_PLUSS}"
 ../ihad test17.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test52.dat  +++52 byte Length File check${TEN_PLUSS}"
 ../ihad test52.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad test256.dat  +++256 byte Length File check${TEN_PLUSS}"
 ../ihad test256.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 #
 echo "$TEN_PLUSS ihad -d test00.dat  +++Zero Length File check in decimal mode${TEN_PLUSS}"
 ../ihad -d test00.dat
@@ -59,7 +66,7 @@ echo "$TEN_PLUSS ihad -H test52.dat  +++Test output sans Hexadecimal${TEN_PLUSS}
 echo "$TEN_PLUSS ihad -A test52.dat  +++Test output sans Ascii${TEN_PLUSS}"
 ../ihad -A test52.dat
 #
-echo "$TEN_PLUSS ihad -f invNum test52.dat  +++Test hex byte Field width with invalid number string${TEN_PLUSS}"
+echo "$TEN_PLUSS ihad -f invNum test52.dat  +++Test hex byte Field width with invalid number $? $REN_PLUSSstring${TEN_PLUSS}"
 ../ihad -f invNum test52.dat
 echo "$TEN_PLUSS ihad -f \"\" test52.dat  +++Test hex byte Field width value set to zero length string${TEN_PLUSS}"
 ../ihad -f "" test52.dat
@@ -79,6 +86,7 @@ echo "$TEN_PLUSS ihad -s test256.dat  +++Test show space characters${TEN_PLUSS}"
 #
 echo "$TEN_PLUSS ihad -h              +++Test help option${TEN_PLUSS}"
 ../ihad -h
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 #
 echo "$TEN_PLUSS ihad -o test.tmp test11.dat test52.dat  +++Test output to a file with 2 input files${TEN_PLUSS}"
 ../ihad -o test.tmp test11.dat test52.dat
@@ -97,9 +105,9 @@ echo "$TEN_PLUSS ihad -c 13 test256.dat    +++Test non-Ascii indicator being lim
 ../ihad -c 13 test256.dat 
 echo "$TEN_PLUSS ihad -c_ test256.dat    +++Test non-Ascii indicator being underscore${TEN_PLUSS}"
 ../ihad -c_ test256.dat 
-echo "$TEN_PLUSS Test non-Ascii indicator specified as an octal number equivalent to asterisk${TEN_PLUSS}"
+echo "$TEN_PLUSS Test non-Ascii indicator specified as an octal number $? $REN_PLUSSequivalent to asterisk${TEN_PLUSS}"
 ../ihad -c '\052' test256.dat 
-echo "$TEN_PLUSS Test non-Ascii indicator specified as an octal number equivalent to underscore${TEN_PLUSS}"
+echo "$TEN_PLUSS Test non-Ascii indicator specified as an octal number $? $REN_PLUSSequivalent to underscore${TEN_PLUSS}"
 ../ihad -c '\137' test256.dat 
 echo "$TEN_PLUSS ihad -c 94 test256.dat    +++Test non-Ascii indicator being decimal equivalent to up-arrow${TEN_PLUSS}"
 ../ihad -c 94 test256.dat 
@@ -162,7 +170,7 @@ echo "$TEN_PLUSS ihad -v10 test52.dat  +++Test Verbosity option positive value l
 echo "$TEN_PLUSS ihad -v+100 test52.dat  +++Test Verbosity option large positive value limiting${TEN_PLUSS}"
 ../ihad -v+100 test52.dat
 #
-echo "$TEN_PLUSS ihad -w sansDigits test11.dat  +++Test Width option with invalid number string${TEN_PLUSS}"
+echo "$TEN_PLUSS ihad -w sansDigits test11.dat  +++Test Width option with invalid number $? $REN_PLUSSstring${TEN_PLUSS}"
 ../ihad -w sansDigits test11.dat
 echo "$TEN_PLUSS ihad -w \"\" test11.dat  +++Test Width option zero length value string${TEN_PLUSS}"
 ../ihad -w "" test11.dat
@@ -185,7 +193,7 @@ echo "$TEN_PLUSS ihad -w 32 test52.dat  +++Test valid Width option value${TEN_PL
 echo "$TEN_PLUSS ihad -w 100 test52.dat  +++Test Width option large positive value limiting${TEN_PLUSS}"
 ../ihad -w 100 test52.dat
 #
-echo "$TEN_PLUSS ihad -L invalidNum test52.dat  +++Test Lines option with invalid number string${TEN_PLUSS}"
+echo "$TEN_PLUSS ihad -L invalidNum test52.dat  +++Test Lines option with invalid number $? $REN_PLUSSstring${TEN_PLUSS}"
 ../ihad -L invalidNum test52.dat
 echo "$TEN_PLUSS ihad -L \"\" test52.dat  +++Test Lines option zero length value string${TEN_PLUSS}"
 ../ihad -L "" test52.dat
@@ -206,7 +214,7 @@ echo "$TEN_PLUSS ihad -L 4 test52.dat  +++Test large Lines option value${TEN_PLU
 echo "$TEN_PLUSS ihad -L +100 test52.dat  +++Test much too large Lines option value${TEN_PLUSS}"
 ../ihad -L +100 test52.dat
 #
-echo "$TEN_PLUSS ihad -B nonNumber test52.dat  +++Test Bytes option with invalid number string${TEN_PLUSS}"
+echo "$TEN_PLUSS ihad -B nonNumber test52.dat  +++Test Bytes option with invalid number $? $REN_PLUSSstring${TEN_PLUSS}"
 ../ihad -B nonNumber test52.dat
 echo "$TEN_PLUSS ihad -B \"\" test52.dat  +++Test Bytes option zero length value string${TEN_PLUSS}"
 ../ihad -B "" test52.dat
@@ -243,10 +251,14 @@ echo "$TEN_PLUSS ihad -d -B 20 -L 4 test52.dat  +++Test Bytes over-rides Lines o
 # Test invalid or dodgy options
 echo "$TEN_PLUSS ihad -a test16.dat  +++Test non-existant option${TEN_PLUSS}"
 ../ihad -a test16.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad -B -L test52.dat  +++Test missing option values ${TEN_PLUSS}"
 ../ihad -B -L test52.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad --begin test52.dat  +++Test non-existant option${TEN_PLUSS}"
 ../ihad --begin test52.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 echo "$TEN_PLUSS ihad -IHAv6 test52.dat  +++Test concatenated option${TEN_PLUSS}"
 ../ihad -IHAv6 test52.dat
+echo "$TEN_PLUSS Shell got Return code number $? $TEN_PLUSS"
 
